stof_doctrine_extensions:
  default_locale: '%kernel.default_locale%'
  orm:
    default:
      timestampable: true
      blameable: true
      ip_traceable: true
      tree: true
      sluggable: true

doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          gedmo_tree:
            prefix: Gedmo\Tree\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
            alias: GedmoTree # (optional) it will default to the name set for the mapping
            is_bundle: false
